version: "3.7"
services:
  compute-api:
    build:
      context: .
      dockerfile: DockerfileCompute
    ports:
      - 8000:80
    links:
      - rate-api
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Docker

  rate-api:
    build:
      context: .
      dockerfile: DockerfileRate
    ports:
      - 8001:80
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Production